### ISSUE TITLE
/pause doesn't work, /setleader doesn't work on pregame

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2062] opened 2021-01-25 04:14 UTC
/pause doesn't work, /setleader doesn't work on pregame

pause is very important because real life things happen, like a doorbell or a phonecall we cannot kill all games because someone needs 1 min to do something else. I would like to be able to open a door, without playing untimed games because I find them boring

**Comment by Zamiell** [comment] 2021-01-25 16:29
/pause was removed
you can (still) pause by right clicking on the timer though

**Comment by padiwik** [comment] 2021-01-26 22:19
Why remove useful chat commands?

**Comment by Zamiell** [comment] 2021-01-26 22:20
how is it useful

**Comment by padiwik** [comment] 2021-01-26 22:20
Some people prefer using chat commands rather than an obscure feature of "right click the timer"

**Comment by Zamiell** [comment] 2021-01-26 22:21
it is much faster to right click the timer, so i dont care about that preference

**Comment by Zamiell** [comment] 2021-01-26 22:22
furthermore, i dont think a documented chat command is any more "obscure" than a documented right click

**Comment by padiwik** [comment] 2021-01-26 22:23
> it is much faster to right click the timer

No if you're already in chat (perhaps you tell your teammate "brb someone's at the door") then it's significantly faster to type out a pause.

**Comment by Zamiell** [comment] 2021-01-26 22:24
thats more of an argument to make a ctrl+p hotkey for pause rather than typing 7 keystrokes

**Comment by Zamiell** [comment] 2021-01-26 22:27
mel see if you can find a reliable way to do the /setleader bug
closing for now since i can't reproduce

**Closed by Zamiell** 2021-01-26 22:27 UTC
