### ISSUE TITLE
did rendering get more expensive?

### ISSUE THREAD

**Issue by erinboyle** [Zamiell/hanabi-live#1014] opened 2020-05-07 05:56 UTC
While playing hanabi tonight, both my computer and my sister's had cpu spike a lot and the fans roar while we were playing. Then when we closed the hanabi tab it all quieted down for both of us. In activity monitor, she had something called "window server" using a bunch of cpu, and I had "google chrome helper (renderer)". Any thoughts?

I'm using chrome browser `Version 81.0.4044.129 (Official Build) (64-bit)`.

**Comment by Zamiell** [comment] 2020-05-07 13:07
dupe of #1003

**Comment by Zamiell** [comment] 2020-05-08 19:51
reopen if still laggy

**Closed by Zamiell** 2020-05-08 19:51 UTC
