### ISSUE TITLE
Show positive clues on the cards

### ISSUE THREAD

**Issue by sephirothx** [Zamiell/hanabi-live#1140] opened 2020-05-29 22:26 UTC
Right now the interface only directly shows touched cards, the clues (positive and negative) are only highlighted in the list on top-right when hovering the desired card. It would be very useful to have positive clues shown direcly on the card.
An idea:

![suggestion](https://user-images.githubusercontent.com/1510856/83310351-04ad6080-a20c-11ea-88f3-7e23c2ea37fc.png)

**Comment by Zamiell** [comment] 2020-05-29 22:52
probably duplicate of #864

**Comment by Zamiell** [comment] 2020-05-31 08:09
in this mockup, it overlaps with the critical indicator

**Comment by Zamiell** [comment] 2020-07-12 08:45
are you still working on this or should i close it?

**Comment by Zamiell** [comment] 2020-07-28 15:49
gonna close since he isn't responding

**Closed by Zamiell** 2020-07-28 15:49 UTC
