### ISSUE TITLE
Proposal: Sudoku Inferences

### ISSUE THREAD

**Issue by Smandon1** [Zamiell/hanabi-live#1469] opened 2020-07-14 20:45 UTC
Empathy makes inferences on your cards, such as removing pips based on seeing other cards out on the table (I think this might be #427).  I think it's neat and wanna see more :P.  I propose an additional layer of inferences (maybe some of this exists already?), similar to solving a sudoku:

If N slots can only be a set of N cards then remove those cards from the possible cards for the other slots.  For example (no variant):
a) N=1: There are three unplayed fives: red, yellow, and blue.  Alice has two fives in slot 1 and 5.  The five in slot 5 has a negative yellow clue.  When Bob draws a red five, that makes Alices fives cross out red from both of her fives.  The only possibility for Alice's five in slot 5 is blue (N=1).  As a result, this should remove blue five from the possible cards for Alice's slot 1 five (since there are no other copies of blue fives).
b) N=2: (replay [here](https://hanabi.live/replay/211426), Smandon's hand on turn 48) All blue cards are seen/known by Alice except a single blue 2 and a single blue 5.  Alice has an existing blue clue on her slot 2 and 3 cards.  One of them has to be a blue 2 and the other has to be a blue 5.  Two slots can only be two cards, therefore the other slots cannot be those two cards and can have them removed as possible cards from Alice's other slots.  This would help slot 1 if the card was drawn after the blue clue.  In the replay, that should mean slot 1 empathy can show green 5.  This is akin to the [naked pair](https://www.learn-sudoku.com/naked-pairs.html) in sudoku.

This would be done iteratively until no new inferences can be made.  Since the max hand size is like 6 cards, I would guess that it shouldn't really be much of a performance hit, if any.  I'd also assume checking/iterating over the N=1 cases first before incrementing N would improve performance if that's a concern.

**Comment by Zamiell** [comment] 2020-07-14 20:47
i'm pretty sure that this is a duplicate of #1459

**Comment by robertos** [comment] 2020-07-14 20:48
No, it's not the same thing. This is talking about making the logic recursive. That one is to make it retroactive

**Comment by asaelr** [comment] 2020-07-14 21:02
It's more than recursive. (recursion is the case N=1)
I would consider implementing this only for the final round. This is when it's most likely to give a useful information. (Even though other situation are possible - for example if I see r5,b5, and I have three cards with a positive 5 clue, and two of them have a negative green).

**Comment by Smandon1** [comment] 2020-07-14 21:06
@asaelr 
> I would consider implementing this only for the final round.
Is that due to performance?  I'm hopeful that it should be performant at any point in the game, given the small hand size.

**Comment by robertos** [comment] 2020-07-14 21:07
I have some ideas on how to impl this, but keeping on my backlog for now. so much more is high priority imo

**Comment by robertos** [comment] 2020-07-24 17:18
Basic solution: every time there's any change to the possibilities map in any card, you'd have to look at all other cards in the hand and try every possibility, and propagate that. if any possibility causes another card to be impossible, that possibility is removed.

e.g. 
your hand has 2 cards
g2, which you know as g24 (1 possibility) and g4 which you know as g4 by elimination.
you try all possibilities for g2, and when you try g4 that would eliminate all possibilities for the other g4. therefore the g2 can't be a g4
and this iterates. every time one of these possibility eliminations causes a possibility to eliminate, you have to do the whole thing again when you're done

**Closed** 2021-02-11 14:45 UTC
Labels: feature
