### ISSUE TITLE
After pressing and releasing spacebar, cursor is locked as magnifying glass and various buttons don't work

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1675] opened 2020-08-23 21:40 UTC

**Comment by timotree3** [comment] 2020-08-23 21:40
```
Uncaught TypeError: t.setEmpathy is not a function
    at x.setEmpathyOnHand (HanabiCard.ts:1200)
    at x.<anonymous> (HanabiCard.ts:1131)
    at x.e._fire (Node.js:1122)
    at x.e._fireAndBubble (Node.js:1096)
    at t.e._fireAndBubble (Node.js:1110)
    at n._mousemove (Stage.js:300)
    at HTMLDivElement.<anonymous> (Stage.js:44)
    at HTMLDivElement.i (helpers.ts:87)
```

**Comment by Zamiell** [comment] 2020-08-23 21:50
unable to reproduce, provide more specific steps

**Comment by timotree3** [comment] 2020-08-23 21:52
enter a game as spectator
then press and release spacebar
then try to click the lobby button

**Comment by Zamiell** [comment] 2020-08-23 21:54
i did those steps and don't get any errors

**Comment by timotree3** [comment] 2020-08-23 21:56
enter a game as spectator
hover your mouse over the play stacks
press and release spacebar
then try to click the lobby button

**Comment by Zamiell** [comment] 2020-08-23 21:57
i did those steps and don't get any errors

**Comment by Zamiell** [comment] 2020-08-23 22:06
should be fixed now

**Closed by Zamiell** 2020-08-23 22:06 UTC
