### ISSUE TITLE
Restarted games still ping users on the waiting list

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1283] opened 2020-06-19 12:56 UTC
and the people who restarted it don't get a warning

**Comment by Zamiell** [comment] 2020-06-21 23:10
unable to reproduce, can you try again and/or provide more specific steps

**Comment by padiwik** [comment] 2020-06-21 23:22
Unfortunately I can't repro, it's really baffling

**Comment by Zamiell** [comment] 2020-06-21 23:37
going to close it then

**Closed by Zamiell** 2020-06-21 23:37 UTC
