### ISSUE TITLE
Content idea: Multinumber deck

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#545] opened 2019-04-16 18:28 UTC
What about a deck that has cards that are touched by every number clue? Sort of like how every color clue touches rainbow.

**Comment by Zamiell** [comment] 2019-04-16 18:32
duplicate of #448

**Comment by Zamiell** [comment] 2019-04-16 18:32
or do you mean one specific suit?

**Comment by hanabirnoob** [comment] 2019-04-16 18:33
Sorry. One specific suit. Sorry for duplicate.

**Comment by Zamiell** [comment] 2019-04-16 18:34
if you mean one specific suit it isn't a duplicate

**Comment by hanabirnoob** [comment] 2019-04-16 18:34
Sorry for confusion.

**Comment by Zamiell** [comment] 2019-04-17 00:18
ok done

**Closed by Zamiell** 2019-04-17 00:18 UTC
