### ISSUE TITLE
TypeScript error: "Failed to get the previously known card identity for card: 45"

### ISSUE THREAD

**Issue by JelleZijlstra** [Zamiell/hanabi-live#2894] opened 2023-12-04 04:03 UTC
I got a TypeScript error on the last play in sudoku + dark null.

```
TypeError: Failed to get the previously known card identity for card: 45
    at Se (https://hanab.live/public/js/bundles/main.6089.min.js:1:46727)
    at Pa.getCardIdentity (https://hanab.live/public/js/bundles/main.6089.min.js:15:25033)
    at Pa.setBareImage (https://hanab.live/public/js/bundles/main.6089.min.js:15:24442)
    at um (https://hanab.live/public/js/bundles/main.6089.min.js:183:17021)
    at Object.AE [as onChange] (https://hanab.live/public/js/bundles/main.6089.min.js:183:19274)
    at i (https://hanab.live/public/js/bundles/main.6089.min.js:183:14083)
    at Object.C [as dispatch] (https://hanab.live/public/js/bundles/main.6089.min.js:172:28786)
    at https://hanab.live/public/js/bundles/main.6089.min.js:198:9443
    at Object.finishOngoingGame (https://hanab.live/public/js/bundles/main.6089.min.js:198:19908)
    at cR.onMessage (https://hanab.live/public/js/bundles/main.6089.min.js:172:27203)
```

<img width="973" alt="Screenshot 2023-12-03 at 8 01 47 PM" src="https://github.com/Hanabi-Live/hanabi-live/assets/906600/d9edb35b-9445-4064-a0ae-1fd57a71a668">

**Comment by Zamiell** [comment] 2023-12-04 04:15
what was the game id?

**Comment by argothiel** [comment] 2023-12-07 18:18
Another one today:
![image](https://github.com/Hanabi-Live/hanabi-live/assets/13932353/e27f4938-b06a-474e-b6f1-202f6605a8c2)

Game 1074353.

**Comment by argothiel** [comment] 2023-12-07 19:44
And during the hypo:
![image](https://github.com/Hanabi-Live/hanabi-live/assets/13932353/d6f29c12-8008-4436-8463-7f84e15ac466)

**Comment by argothiel** [comment] 2023-12-10 03:41
![image](https://github.com/Hanabi-Live/hanabi-live/assets/13932353/d69f6445-c0ec-4d6e-8d5e-bdbfe07c46cf)

Game 1075985.

**Comment by argothiel** [comment] 2023-12-10 17:19
Is a duplicate of #2876?

**Comment by Zamiell** [comment] 2023-12-16 15:14
ok Rama has been working on this.

today we added new error messages for when the deck gets out of sync.

@argothiel let me know if you get any new error messages lately, and hopefully with the steps to recreate the error message from scratch

**Comment by argothiel** [comment] 2023-12-18 15:26
I didn't get any new messages right after the game recently. I got the "A hypoBack action was dispatched with a null hypothetical state" during the hypo, but that might be unrelated.

**Comment by kesslermaximilian** [comment] 2023-12-19 11:52
Not the exact same error, but I just got this stacktrace while watching a 2p-NoVar game. I did not take any special actions except spectating.
![image](https://github.com/Hanabi-Live/hanabi-live/assets/82446011/b8e87163-c7d4-403a-bc11-de5da1804e4c)

Clear Stacktrace:
```
TypeError: Failed to get card of order 15 from the deck.
    at ve (https://hanab.live/public/js/bundles/main.6226.min.js:5:285677)
    at si (https://hanab.live/public/js/bundles/main.6226.min.js:32:65293)
    at hV (https://hanab.live/public/js/bundles/main.6226.min.js:34:41438)
    at go (https://hanab.live/public/js/bundles/main.6226.min.js:34:40954)
    at https://hanab.live/public/js/bundles/main.6226.min.js:34:41028
    at qi.finishedTweening (https://hanab.live/public/js/bundles/main.6226.min.js:34:24302)
    at Object.onFinish (https://hanab.live/public/js/bundles/main.6226.min.js:13:97737)
    at e.onFinish (https://hanab.live/public/js/bundles/main.6226.min.js:13:95813)
    at tween.onFinish (https://hanab.live/public/js/bundles/main.6226.min.js:12:122920)
    at e.fire (https://hanab.live/public/js/bundles/main.6226.min.js:12:119021)
```

Since NoVar clearly has at least 16 cards in the deck, there is probably some race condition going on, i.e. the deck has not been updated yet, but the client already wanted to access the card in the deck? I would say the error occurred around a time where card 15 (= the 16th card in the deck) was drawn, so this could be the problem here. But I cannot say for sure if this was the case.

**Comment by Zamiell** [comment] 2023-12-19 14:32
Yeah I think that is a separate issue, it looks like your internet lagged and you got an action out of order. This kind of thing isn't supposed to happen [WebSocket can't deliver messages out of order](https://stackoverflow.com/questions/11804721/can-websocket-messages-arrive-out-of-order).

**Comment by Zamiell** [comment] 2023-12-19 14:34
The stack trace isn't interesting, I'd be interested in seeing what were the actions received by the server before and after the error message.

**Closed as completed** 2024-05-24 19:21 UTC
Labels: bug
