### ISSUE TITLE
Bugs in hypothetical

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1713] opened 2020-08-29 21:49 UTC
Over the past few days, I've had two new bugs in hypothetical:
1) clue count is zero, but it is impossible to discard
2) clue count is not zero, but it is impossible to give a clue (the clue area is crossed out and says no clues, even though the clue count is positive; in both cases the clue count is correct).
Also, not sure if this is documented, but sometimes the show drawn cards button is greyed out, but this is fixed by refreshing the page.

**Comment by Zamiell** [comment] 2020-08-29 22:42
provide reliable steps to reproduce

**Comment by chmallon** [comment] 2020-08-30 12:07
>  Also, not sure if this is documented, but sometimes the show drawn cards button is greyed out, but this is fixed by refreshing the page.
I noticed this, too, for a while now (>2 weeks?), but it just happens somtimes and I have not noticed any specific trigger so far. ):

**Comment by TheDaniMan** [comment] 2020-08-30 17:03
None of these happen consistently, but I've seen each at least twice; will provide steps if I figure it out.

**Comment by padiwik** [comment] 2020-09-28 02:32
1. is #1749 
2. looks like #1703  - have you seen that bug recently? that was fixed a month ago, and zam may or may not have updated the website when the fix happened
3. is #1747 probably

i recommend closing this issue

**Comment by Zamiell** [comment] 2020-09-29 04:53
fixed thanks to padi

**Closed by Zamiell** 2020-09-29 04:53 UTC
