### ISSUE TITLE
Hypothetical in Alternating Clues Broken

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1135] opened 2020-05-29 14:37 UTC
When entering hypothetical in Alternating Clues, only rank clues are given, so you are unable to switch between clues in hypothetical.

**Comment by Zamiell** [comment] 2020-05-29 14:37
dupe of #985, please search for existing issues before you open them

**Closed by Zamiell** 2020-05-29 14:37 UTC
