### ISSUE TITLE
Muddy Prism

### ISSUE THREAD

**Issue by sephirothx** [Zamiell/hanabi-live#1701] opened 2020-08-27 22:57 UTC
Sounds fun and challenging

**Comment by Zamiell** [comment] 2020-08-28 14:25
dupe of 1708

**Closed by Zamiell** 2020-08-28 14:25 UTC

**Comment by padiwik** [comment] 2020-08-29 02:26
zam are you against linking issues through github's interface? (i.e. `#1708` to automatically make a link)

I've seen you often don't link relevant issues/prs
