### ISSUE TITLE
Create push notifications for users without Discord

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#5] opened 2018-01-03 20:42 UTC
To allow hanabi players that do not actively use Discord, we should implement the functionality of push notifications so that users get told someone is interested in playing a game, even when they are not on the website. This of course would be an optional feature since websites always ask the user if they want notifications.

**Comment by Zamiell** [comment] 2018-01-09 19:26
is this just a duplicate of #3 ?

**Comment by RaKXeR** [comment] 2018-01-11 10:20
no, they are different things.

**Comment by Zamiell** [comment] 2018-01-11 15:07
explain how they are different

**Comment by RaKXeR** [comment] 2018-01-11 15:45
the key feature of what I'm suggesting here is the ability to get notified **without having the website open**. This would likely work by having the server check it's own chat for messages that mention the player or @here, and then notifying everyone that has notifications on. #3 is talking about signaling to people on the web page that you want to play, and keeping the tab open at all times. The main difference is that what I'm talking about notifies people that weren't necessarily hunting for an hanabi game but would join it, while #3 is intended for people actively seeking games.

**Comment by Zamiell** [comment] 2018-01-11 16:12
on the contrary, in #3, the user will get a browser notification without having the website open

**Comment by RaKXeR** [comment] 2018-01-11 16:14
> Joining a table, **closing the page**, and entering a replay are all enough to cancel the notification.

**Comment by Zamiell** [comment] 2019-01-08 05:04
it will be weird to have both a discord waiting list and a browser notification waiting list

**Closed by Zamiell** 2019-01-08 05:04 UTC
