### ISSUE TITLE
Critical indicators on your own hand disappear when dragging any card from your hand

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1158] opened 2020-06-01 19:08 UTC

**Comment by robertos** [comment] 2020-06-02 06:02
@padiwik Can you give an example? During the game, you should never see any crit indicators on your own hand, since they're disabled in empathy.

**Comment by Zamiell** [comment] 2020-06-02 13:11
you can be playing a fully "filled-in" card though

**Comment by padiwik** [comment] 2020-06-02 13:53
@robertos I remember it happened in game 190553 where I had a bunch of filled in fives. But I can't get it to happen in the replay - maybe you need to be in my perspective for it to happen, for which I need someone to join since perspective shifting doesn't work when you're alone in a shared replay.

**Comment by Zamiell** [comment] 2020-06-02 13:55
> perspective shifting doesn't work when you're alone in a shared replay.

actually it does work, try it

**Comment by padiwik** [comment] 2020-06-02 13:56
> actually it does work, try it

are my cards supposed to be hidden?

**Comment by Zamiell** [comment] 2020-06-02 13:57
what do you mean

**Comment by padiwik** [comment] 2020-06-02 13:58
The purpose of perspective shifting is so that your hand is in empathy view during review, right? It doesn't seem to do anything different when I right click my name

**Comment by sephirothx** [comment] 2020-06-02 13:59
> @padiwik Can you give an example? During the game, you should never see any crit indicators on your own hand, since they're disabled in empathy.

you see crit indicators on critical cards in your hand if you have full information

**Comment by Zamiell** [comment] 2020-06-02 14:03
i literally just said that

**Comment by Zamiell** [comment] 2020-06-02 14:03
> The purpose of perspective shifting is so that your hand is in empathy view during review, right?

no, it is simply to shift the position of the players

**Comment by Zamiell** [comment] 2020-06-02 14:04
in spectator mode though it will do that

**Comment by Zamiell** [comment] 2020-06-02 14:04
you could do a !replay game if you want to try reproducing it

**Comment by padiwik** [comment] 2020-06-02 14:05
Related: Should critical indicators appear in empathy mode for filled in cards during review? They appear in game.

**Comment by Zamiell** [comment] 2020-06-02 14:06
i dont see why they wouldn't

**Comment by padiwik** [comment] 2020-06-02 14:07
they dont, #1162

**Comment by padiwik** [comment] 2020-06-02 14:19
Easiest way to reproduce @robertos is to make a 2 player game and fully clue a critical card. Then have the player with the clued card try to drag any card, the indicators will disappear.

**Comment by robertos** [comment] 2020-06-02 19:00
Sure. @Zamiell feel free to assign this and #1162 to me.

**Closed** 2020-06-03 06:05 UTC
